project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Welcome to R
        href: webR-welcome/index.qmd
      - text: Welcome to Git
        href: git-slides/index.qmd
        icon: git # see https://icons.getbootstrap.com/
      
format:
  html:
    theme: [slate, styles.scss]
    mainfont: monospace
